<?php
  		mxi_includes_start("product_info_contain_subcat2.php");
  		require(basename("product_info_contain_subcat2.php"));
  		mxi_includes_end();
?> 
<?php
  mxi_includes_start("product_info_contain_prosub2.php");
  require(basename("product_info_contain_prosub2.php"));
  mxi_includes_end();
?>