<?php
  		mxi_includes_start("product_info_contain_cat.php");
  		require(basename("product_info_contain_cat.php"));
  		mxi_includes_end();
?> 
<?php
  mxi_includes_start("product_info_contain_pro.php");
  require(basename("product_info_contain_pro.php"));
  mxi_includes_end();
?>