<?php
  		mxi_includes_start("sell_info_subcat4.php");
  		require(basename("sell_info_subcat4.php"));
  		mxi_includes_end();
?> 
<?php
  mxi_includes_start("sell_info_prosub3.php");
  require(basename("sell_info_prosub3.php"));
  mxi_includes_end();
?>