<?php
  		mxi_includes_start("sell_info_subcat1.php");
  		require(basename("sell_info_subcat1.php"));
  		mxi_includes_end();
?> 
<?php
  mxi_includes_start("sell_info_procat.php");
  require(basename("sell_info_procat.php"));
  mxi_includes_end();
?>