<?php
  		mxi_includes_start("product_info_contain_subcat4.php");
  		require(basename("product_info_contain_subcat4.php"));
  		mxi_includes_end();
?> 
<?php
  mxi_includes_start("product_info_contain_prosub4.php");
  require(basename("product_info_contain_prosub4.php"));
  mxi_includes_end();
?>