<?php
  		mxi_includes_start("buy_info_subcat2.php");
  		require(basename("buy_info_subcat2.php"));
  		mxi_includes_end();
?> 
<?php
  mxi_includes_start("buy_info_prosub1.php");
  require(basename("buy_info_prosub1.php"));
  mxi_includes_end();
?>